### ISSUE TITLE
Questions about the 8 bit display

### ISSUE THREAD

**Issue by HasanTheSyrian** [3KUdelta/Futaba-VFD-16bit_ESP32#2]
Hello, I am confused about a few things.

What exactly is EN? It says to solder a "blob" between EN and VCC, on the silkscreen it also says "short power on". I don't know what that means.

What is the driver IC? I think it might be the PT6302 but I'm not sure.

I have tried looking for the original author to contact but found nothing about him.

Thanks in advance.

**Comment by twaymouth** [comment]
EN enables the display, taking EN high, I.e shorting it to VCC enables the display however it could also be driven from a microcontrollers gpio for example. If you want the display always on you can just solder j1 closed which will take EN high. 

Not sure at this stage what the driver ic is, I have ordered a few variations of this display to play with and will let you know once they arrive.

**Comment by HasanTheSyrian** [comment]
Thank you for your answer. I actually have ordered the display and received it but I haven't had the time to test it yet.   

From what I found the controller IC is the PT6302.
Here is everything I found about the display:

https://github.com/3KUdelta/Futaba-VFD-16bit_ESP32/tree/main
https://github.com/hexesdesu/ESP32VFDClock
https://github.com/sfxfs/ESP32-VFD-8DM-Arduino
https://github.com/Reboot93/VFD-desktop-clock-micropython
https://community.dfrobot.com/makelog-310356.html
https://timewitharduino.blogspot.com/2021/04/
https://blog.csdn.net/sxhexin/article/details/107284089

https://github.com/3KUdelta/Futaba-VFD-16bit_ESP32/blob/main/documents/VFD%E5%B1%8F%E6%89%8B%E5%86%8C.pdf
https://pdf1.alldatasheet.com/datasheet-pdf/view/391603/PTC/PT6302.html

I'll keep this open for when your units arrive.
